# spring.data.mongodb.uri=mongodb+srv://manavdevsharma526:cMCFAbdRLZa0dtcc@cluster0.lj9qm.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
# spring.data.mongodb.database=UserEntry
# # spring.data.mongodb.database=JournalEntry
# spring.data.mongodb.auto-index-creation=true
# spring.data.mongodb.uri=mongodb+srv://manavdevsharma526:cMCFAbdRLZa0dtcc@cluster0.lj9qm.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
# spring.data.mongodb.database=JournalEntry
# spring.data.mongodb.database=UserEntry
# spring.data.mongodb.auto-index-creation=true
# server.port=8080
# spring.data.mongodb.uri=mongodb+srv://manavdevsharma526:cMCFAbdRLZa0dtcc@cluster0.lj9qm.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
# spring.data.mongodb.database=UserEntry
# spring.data.mongodb.database=JournalEntry

# spring.data.mongodb.database=JournalEntry
spring.data.mongodb.host=localhost
spring.data.mongodb.database=UserEntry
spring.data.mongodb.port=27017