
# spring.data.mongodb.database=UserEntry
# # spring.data.mongodb.database=JournalEntry
# spring.data.mongodb.auto-index-creation=true
# spring.data.mongodb.database=JournalEntry
# spring.data.mongodb.database=UserEntry
spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.host=localhost
spring.data.mongodb.database=UserEntry
spring.data.mongodb.port=27017
